name: daily-site-refresh

on:
  workflow_dispatch:
  schedule:
    # 13:05 UTC ≈ 9:05am US/Eastern (adjust if desired)
    - cron: "5 13 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pillow yfinance

      - name: Build daily data/snapshots
        run: |
          python scripts/make_heatmap_snapshot.py
          # You can add calendar later if you want:
          # python scripts/make_calendar_today.py

      - name: Commit updates
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/heatmap-snapshot.png docs/heatmap.snapshot.png
          git commit -m "Daily: refresh heat map snapshot" || echo "No changes"
          git push
