name: daily-site-refresh

on:
  schedule:
    - cron: '0 12 * * 1-5'   # adjust for your timezone (this is 8am ET)
  workflow_dispatch:

jobs:
  heatmap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Playwright
        run: |
          npm init -y
          npm i -D playwright
          npx playwright install --with-deps chromium

      - name: Snapshot Finviz heatmap → docs/heatmap-snapshot.png
        run: |
          node - <<'JS'
          const { chromium } = require('playwright');
          (async () => {
            const browser = await chromium.launch();
            const ctx = await browser.newContext({ viewport: { width: 1400, height: 900 }});
            const page = await ctx.newPage();
            await page.goto('https://finviz.com/map.ashx', { waitUntil: 'networkidle' });
            // If a cookie banner ever appears, you could dismiss it here.
            await page.waitForTimeout(2000);
            await page.screenshot({ path: 'docs/heatmap-snapshot.png', fullPage: true });
            await browser.close();
          })();
          JS

      - name: Commit updated snapshot
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/heatmap-snapshot.png
          git diff --cached --quiet || git commit -m "Update heatmap snapshot"
          git push
