name: daily-site-refresh
on:
  schedule: [ { cron: "0 10 * * *" } ]   # ≈ 6:00am ET; adjust for DST if you want
  workflow_dispatch:

permissions: { contents: write }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: |
          python -m pip install --upgrade pip
          pip install playwright requests feedparser beautifulsoup4 yfinance
          python -m playwright install --with-deps chromium
      - name: Build daily data/snapshots
        run: |
          python "Website/update_dashboard.py" "Website"
      - name: Commit updates
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add Website/*.json Website/*.png || true
          git commit -m "Daily refresh" || echo "No changes"
          git push

