name: intraday-ticker

on:
  workflow_dispatch: {}
  schedule:
    # Every 15 minutes 13:30–20:00 UTC (9:30–4:00 ET) Mon–Fri
    - cron: "*/15 13-20 * * 1-5"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install "yfinance>=0.2.44" pandas numpy lxml

      - name: Generate ticker-prices.json
        run: |
          python scripts/make_ticker_json.py

      - name: Commit changes (only if file changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain docs/ticker-prices.json)" ]; then
            git add docs/ticker-prices.json
            git commit -m "Update intraday ticker [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
