name: intraday-ticker

on:
  workflow_dispatch:
  schedule:
    # every 10 minutes (UTC). Adjust as you like.
    - cron: "*/10 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install yfinance requests pillow

      - name: Generate ticker-prices.json + winners/losers
        run: |
          python scripts/make_ticker_json.py
          python scripts/make_winners_losers.py

      - name: Commit intraday files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/ticker-prices.json docs/winners.json docs/losers.json
          git commit -m "Intraday: update ticker + winners/losers" || echo "No changes"
          git push
